#!/usr/bin/env python
# File created on 09 Feb 2010
from __future__ import division

__author__ = "Rob Knight"
__copyright__ = "Copyright 2011, The QIIME Project"
__credits__ = ["Rob Knight","Justin Kuczynski","Greg Caporaso"]
__license__ = "GPL"
__version__ = "1.4.0-dev"
__maintainer__ = "Daniel McDonald"
__email__ = "wasade@gmail.com"
__status__ = "Development"
 

from qiime.util import parse_command_line_parameters
from qiime.util import make_option
from qiime.pycogent_backports.parse_biom import parse_biom_table
from qiime.parse import parse_taxonomy_to_otu_metadata

script_info={}
script_info['brief_description']="""Add taxa to OTU table"""
script_info['script_description']="""This script adds taxa to an OTU table."""
script_info['script_usage']=[]
script_info['script_usage'].append(("""Example:""","""Add taxa to otu file from otus.txt from file taxa.txt:""","""add_taxa.py -i otus.txt -t taxa.txt"""))
script_info['output_description']="""The result of this script is written to the specified file."""
script_info['required_options']=[\
    make_option('-i','--input_fp',type='existing_filepath',
                help='path to input otu table file in biom format'),
    make_option('-o','--output_fp',type='new_filepath',
                help='path to output file in biom format'),
    make_option('-t','--taxonomy_fp',type='existing_filepath',
                help='path to input taxonomy file (as generated by assign_taxonomy.py)'),
]

script_info['optional_options']=[]
script_info['version'] = __version__

def main():
    option_parser, opts, args = parse_command_line_parameters(**script_info)
    
    output_f = open(opts.output_fp,'w')
    observation_metadata = parse_taxonomy_to_otu_metadata(\
                            open(opts.taxonomy_fp,'U'))

    otu_table = parse_biom_table(open(opts.input_fp,'U'))
    otu_table.addObservationMetadata(observation_metadata)
    
    output_f.write(otu_table.getBiomFormatJsonString())
    output_f.close()
    
    
    

if __name__ == "__main__":
    main()
