#! /bin/bash
wipe() { for i in "$*"; do echo "if [ -e $i ]; then rm $i; echo $i removed; else echo $i not found; fi"| sudo bash; done; }
wipe /root/.ssh/*
wipe ~/.ssh/*
wipe /etc/ssh/ssh_host_dsa_key
wipe /etc/ssh/ssh_host_dsa_key.pub
wipe /etc/ssh/ssh_host_key
wipe /etc/ssh/ssh_host_key.pub
wipe /etc/ssh/ssh_host_rsa_key
wipe /etc/ssh/ssh_host_rsa_key.pub
wipe ~/.bash_history
wipe /root/.bash_history
