#!/bin/bash
# $Id$
echo $* >> /tmp/dispatch
N="$1"
DEST=`sed "${N}q;d" < ~/hosts.slave`
shift
if [ $DEST != "localhost" ]
then
    exec ssh -i ~/.ssh/cluster.pem $DEST "cd ~/sandbox; export PATH=$PATH; export PYTHONPATH=$PYTHONPATH; $*"
else
    exec $*
fi
